name: err
description: Error data structures for fine-grained control over errors. It is
  possible to use errors as values like in Go
homepage: https://github.com/synw/err
version: 1.0.0

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  enum_to_string: ^1.0.14
  extra_pedantic: ^1.2.0
  hive: ^1.4.4+1
  meta: ^1.2.4
  pedantic: ^1.9.2
